exports.list = ["8 Mile",
                "28 Days Later",
                "101 Dalmatians",
                "300",
                "2001: A Space Odyssey",
                "A Clockwork Orange",
                "A.I. Artificial Intelligence",
                "Air Bud",
                "Air Force One",
                "Airplane!",
                "Aladdin",
                "Alice in Wonderland",
                "Aliens",
                "An American Tail: Fivel Goes West",
                "Animal House",
                "Apollo 13",
                "Austin Powers: International Man of Mystery",
                "Babe",
                "Back to the Future",
                "Back to the Future Part II",
                "Back to the Future Part III",
                "Bambi",
                "Batman Begins",
                "Batman Returns",
                "Beetlejuice",
                "Being John Malkovich",
                "Better Off Dead",
                "Beverly Hills Cop",
                "Big",
                "The Big Lebowski",
                "Big Trouble in Little China",
                "Bill and Ted's Excellent Adventure",
                "Blank Check",
                "Blazing Saddles",
                "The Blues Brothers",
                "Boyhood",
                "Boyz n the Hood",
                "Brazil",
                "The Breakfast Club",
                "A Bug's Life",
                "The Butterfly Effect",
                "Cabin Fever",
                "Cabin in the Woods",
                "Cast Away",
                "Catch Me If You Can",
                "Clerks",
                "Close Encounters Of The Third Kind",
                "Con Air",
                "Contact",
                "Cool Runnings",
                "Cube 2: Hypercube",
                "Dawn of the Dead",
                "Death to Smoochy",
                "Die Hard",
                "District 9",
                "Donnie Darko",
                "Dr. Strangelove: Or How I Learned to Stop Worrying and Love The Bomb",
                "Dune",
                "Dunston Checks In",
                "Ed Wood",
                "Edward Scissorhands",
                "Event Horizon",
                "The Evil Dead",
                "Face/Off",
                "Fantastic Mr. Fox",
                "Fargo",
                "The Fast and the Furious",
                "Ferris Bueller's Day Off",
                "The Fifth Element",
                "Fight Club",
                "Finding Nemo",
                "Flubber",
                "Frozen",
                "Galaxy Quest",
                "Ghostbusters",
                "Good Burger",
                "The Goonies",
                "Gravity",
                "Gremlins",
                "Groundhog Day",
                "Grown Ups 2",
                "Guardians of the Galaxy",
                "Hackers",
                "Happy Gilmore",
                "Harry Potter and the Sorcerer's Stone",
                "Home Alone 2: Lost in New York",
                "Honey, I Shrunk The Kids",
                "Hook",
                "The Hudsucker Proxy",
                "The Hunger Games",
                "The Hunt for Red October",
                "I, Robot",
                "Inception",
                "The Incredibles",
                "Independence Day",
                "Indiana Jones and the Raiders of the Lost Ark",
                "Iron Giant",
                "Iron Man",
                "It's a Mad, Mad, Mad, Mad World",
                "James and the Giant Peach",
                "Jaws",
                "Jumanji",
                "Jurassic Park",
                "The Karate Kid",
                "Kill Bill: Volume 1 and 2",
                "King Kong",
                "Kung Fu Panda",
                "Labyrinth",
                "The Last Starfighter",
                "The Life Aquatic",
                "The Lion King",
                "Lord of the Rings: The Fellowship of the Ring",
                "Manos: The Hands of Fate",
                "The Matrix",
                "Men in Black",
                "Monsters Inc.",
                "Monty Python and the Holy Grail",
                "Mulan",
                "Mystery Men",
                "The Nightmare Before Christmas",
                "O Brother, Where Art Thou?",
                "Ocean's Eleven",
                "Operation Dumbo Drop",
                "Outbreak",
                "Pacific Rim",
                "Paul Blart: Mall Cop 2",
                "Pee-wee's Big Adventure",
                "Peter Pan",
                "Pirates of the Caribbean: The Curse of the Black Pearl",
                "Pitch Black",
                "Planet of the Apes",
                "Point Break",
                "The Princess Bride",
                "Pulp Fiction",
                "Ratatouille",
                "The Ring",
                "RoboCop",
                "The Room",
                "The Sandlot",
                "Scott Pilgrim vs. The World",
                "Seven Samurai",
                "Shaun of the Dead",
                "The Shining",
                "Shrek",
                "Signs",
                "Silence of the Lambs",
                "The Sixth Sense",
                "Snow White and the Seven Dwarfs",
                "The Social Network",
                "Space Jam",
                "Speed",
                "Spirited Away",
                "Stand By Me",
                "Star Wars: The Phantom Menace",
                "Star Wars: A New Hope",
                "Stargate",
                "Super Mario Bros: The Movie",
                "Teenage Mutant Ninja Turtles",
                "Terminator 2: Judgement Day",
                "That Thing You Do!",
                "The Thing",
                "THX 1138",
                "Titan AE",
                "Titanic",
                "Top Gun",
                "Total Recall",
                "Toy Story",
                "Tremors",
                "Tron",
                "The Truman Show",
                "Twelve Monkeys",
                "Twister",
                "UHF",
                "V for Vendetta",
                "WALL-E",
                "WarGames",
                "Weekend at Bernie's",
                "Who Framed Roger Rabbit",
                "Willy Wonka and the Chocolate Factory",
                "Wreck-it Wralph",
                "Zardoz",
                "Zoolander"
              ];

exports.randomMovie = function () {
  return exports.list[Math.floor(Math.random()*exports.list.length)];
};

exports.getThree = function () {
  var swapElements = function (n) {
    var temp = exports.list[n];
    var randomIndex = Math.floor(Math.random()*(exports.list.length - 3) + 3);
    exports.list[n] = exports.list[randomIndex];
    exports.list[randomIndex] = temp;
  };

  swapElements(0);
  swapElements(1);
  swapElements(2);

  return exports.list.slice(0, 3);
};
